### ISSUE TITLE
Why copy todos into component state?

### ISSUE THREAD

**Issue by stubailo** [ooade/ApolloSimpleStarter#3]
You should be able to just use the todos from the props directly, and use the `update` method on the Apollo mutation to insert the new item much the same way you do it with state right now.

**Comment by ooade** [comment]
I did that earlier with ~~updateQueries~~, but i was looking for a way to update the Redux state before sending the data to the server then append the generated id after the mutation has occurred. 
I think it's more or less like optimisticResponse???

But optimisticResponse kinda breaks my transition :sweat_smile:

**Comment by ooade** [comment]
Just noticed! My current implementation does the same thing the `update` method should do, i'll make a PR to implement that instead.

**Comment by stubailo** [comment]
Yep - should be quite simple, let me know if you run into trouble :]

**Comment by ooade** [comment]
Thanks a lot. I've implemented it locally. Playing around with the css transitions and optimisticResponse that's why i haven't pushed it :rofl:

**Comment by stubailo** [comment]
I think if you get it right that will be a great example for others to follow!
